(lang dune 3.19)

(name tryOcaml1)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name tryOcaml1)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends 
  ocaml
  (alcotest :with-test) 
  (timedesc (>= 3.1.0))))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
